theme: jekyll-theme-minimal
title: Antonio (Tony) C. Rodriguez
description: Harvard Prize Postdoctoral Fellow · Astrophysicist
logo: rodriguez_antonio.png

permalink: /blog/:title/

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
